<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.17">
  <POU Name="FB_Module" Id="{245e3b14-486a-4d3d-b47e-47bddc614d02}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Module
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>