<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Example" Id="{bebb6320-5f8d-442b-bc9e-479d8a85bedf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Example
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>